### ISSUE TITLE
Add amazonses.com to whitelist clients 

### ISSUE THREAD

**Issue by n3storm** [schweikert/postgrey#35]
amazonses.com* is the domain used by amazon service for transactional mailing and doesn't retry after greylisted so email is rejected for ever.

* https://aws.amazon.com/es/ses/

**Comment by SonRiab** [comment]
The regions should be whitelisted as well (for the same reasons).
smtp-out.us-east-1.amazonses.com
smtp-out.us-west-2.amazonses.com
smtp-out.eu-west-1.amazonses.com
See: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html

**Comment by schweikert** [comment]
Fixed in f9fb0ec0

**Comment by hostingnuggets** [comment]
@schweikert why didn't you add the hosts as suggested by @SonRiab but only added amazonses.com in f9fb0ec ?

**Comment by RandieM** [comment]
I have the same problem with emails from amazonses constantly getting greylisted. Has this been resolved somehow, because the changes in f9fb0ec did not seem to help in my case?

**Comment by karamble** [comment]
This issue is still present. Amazon Cloud ALLWAYS runs into greylist! BAD

**Comment by RandieM** [comment]
This is affecting many of our customers. It would be great if it could get fixed.

**Comment by pjperry** [comment]
For now, just add amazonses.com to your postgrey_whitelist_clients.local file to whitelist these.

**Comment by schweikert** [comment]
What version of postgrey are you using? amazonses.com is already whitelisted, but it looks like you have encountered the problem described in #32, fixed in version 1.37.

**Comment by KevinTriplett** [comment]
I'm running 1.34 which is the latest Debian package. I downloaded the 2017-02-09 whitelist_client list from the website but still won't allow amazonses.com to send email to my client.

**Comment by KevinTriplett** [comment]
I may have fixed my particular problem: for some reason, postgrey was not stopping even when I apt-get removed it. It was like a zombie process, I had to do a kill -9. Now with 1.34 and the newest whitelist_clients.

After reinstalling, I'm still not able to restart postgrey, I have to manually kill it. But at least I'm accepting email from amazonses, whew. BTW thanks for such a nice oss <3
